import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../styles/globals.css'

import { Navbar } from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main>
      <Navbar />
      {children}
    </main>
  )
}
